### ISSUE TITLE
[Help] unable to launch project 

### ISSUE THREAD

**Issue by rookie-12** [HighVibe/hvn#87]
pubspec.yaml

```
name: highvibe
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: 1.0.5
  audioplayers: ^0.15.1
  camera: ^0.5.7+4
  dio: ^3.0.9
  easy_permission_validator: ^2.0.0
  flutter_apns: ^1.1.0
  flutter_local_notifications: ^1.4.1
  flutter_svg: ^0.17.4
  provider: ^4.0.5
  stream_chat_flutter: ^0.2.0-alpha+2
  virtual_keyboard: ^0.1.4
  # Firebase
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.4
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.1.1
  # UI
  awesome_dialog: ^0.1.1
  badges: ^1.1.0
  bot_toast: ^2.2.1
  bubble: ^1.1.9+1
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  flutter_inner_drawer: ^0.5.4
  flutter_staggered_grid_view: ^0.3.0
  font_awesome_flutter: ^8.5.0
  photo_view: ^0.9.1
  popup_menu: ^1.0.5
  pull_to_refresh: ^1.5.8
  shimmer: ^1.0.1
  styled_widget: ^0.0.6
  # State Managment
  analyzer: ^0.39.2+1
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.1.2
  freezed_annotation: ^0.7.1
  hive_flutter: ^0.3.0+1
  hive: ^1.4.1+1
  mobx: ^1.1.1
  # Utils
  built_collection: ^4.3.2
  built_value: ^7.1.0
  email_validator: ^1.0.4
  google_fonts: ^0.3.9
  image_picker: ^0.6.3+1
  intl: ^0.16.1
  json_annotation:
  logger: ^0.8.3
  path_provider: ^1.5.1
  permission_handler: ^5.0.0
  timeago: ^2.0.25
  url_launcher: ^5.4.1

dev_dependencies:
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  built_value_test: ^7.1.0
  json_serializable: ^3.3.0
  mobx_codegen: ^1.0.3
  mockito: ^4.1.1
  # flutter_test:
  #   sdk: flutter


```

issue:
```
The current Dart SDK version is 2.7.0-dev.2.1.flutter-8b8894648f.



Because highvibe depends on freezed_annotation >=0.3.1 which requires SDK version >=2.7.0 <3.0.0, version solving failed.
pub get failed (1; Because highvibe depends on freezed_annotation >=0.3.1 which requires SDK version >=2.7.0 <3.0.0, version solving failed.)
```

Flutter doctor Output
```
[√] Flutter (Channel unknown, v1.13.2, on Microsoft Windows [Version 10.0.17763.1158], locale en-US)
    • Flutter version 1.13.2 at D:\flutter
    • Framework revision 4944622b5d (5 months ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Redmi Note 7 Pro • ce44cc49 • android-arm64 • Android 9 (API 28)

• No issues found!

```
